# Generated by Django 2.2 on 2020-04-26 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=14)),
                ('address', models.CharField(max_length=34)),
                ('name', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='notarised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('chain', models.CharField(max_length=12)),
                ('block_hash', models.CharField(max_length=64)),
                ('block_ht', models.PositiveIntegerField()),
                ('notaries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), size=13)),
                ('prev_block_hash', models.CharField(max_length=64)),
                ('prev_block_ht', models.PositiveIntegerField()),
            ],
        ),
    ]
