# Generated by Django 2.2 on 2020-04-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notarised',
        ),
    ]
