# Generated by Django 2.2 on 2020-04-26 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0002_delete_notarised'),
    ]

    operations = [
        migrations.CreateModel(
            name='notarised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('chain', models.CharField(max_length=12)),
                ('block_hash', models.CharField(max_length=64)),
                ('block_ht', models.PositiveIntegerField()),
                ('notaries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), size=13)),
                ('prev_block_hash', models.CharField(max_length=64)),
                ('prev_block_ht', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'notarised',
            },
        ),
        migrations.AddConstraint(
            model_name='notarised',
            constraint=models.UniqueConstraint(fields=('txid',), name='unique_txid'),
        ),
    ]
