# Generated by Django 2.2 on 2020-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0003_auto_20200426_1649'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mined',
            constraint=models.UniqueConstraint(fields=('block',), name='unique_block'),
        ),
        migrations.AlterModelTable(
            name='mined',
            table='mined',
        ),
    ]
