# Generated by Django 2.2 on 2020-04-27 14:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0004_auto_20200426_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='mined_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary', models.CharField(max_length=64)),
                ('sum_mined', models.DecimalField(decimal_places=8, max_digits=18)),
                ('max_mined', models.DecimalField(decimal_places=8, max_digits=18)),
                ('timestamp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mined_count',
            },
        ),
        migrations.CreateModel(
            name='notarised_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary', models.CharField(max_length=64)),
                ('btc_count', models.PositiveIntegerField()),
                ('antara_count', models.PositiveIntegerField()),
                ('third_party_count', models.PositiveIntegerField()),
                ('other_count', models.PositiveIntegerField()),
                ('total_ntx_count', models.PositiveIntegerField()),
                ('json_count', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'notarised_count',
            },
        ),
    ]
