# Generated by Django 2.2 on 2020-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0005_mined_count_notarised_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mined',
            name='block_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notarised',
            name='block_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
