# Generated by Django 2.2 on 2020-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0006_auto_20200428_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='mined_count',
            name='last_mined',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
