# Generated by Django 2.2 on 2020-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0007_mined_count_last_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='mined',
            name='txid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
