# Generated by Django 2.2 on 2020-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0008_mined_txid'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary_id', models.PositiveIntegerField()),
                ('notary_name', models.CharField(max_length=34)),
                ('address', models.CharField(max_length=34)),
                ('pubkey', models.CharField(max_length=66)),
                ('season', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.AlterField(
            model_name='mined',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='addresses',
            constraint=models.UniqueConstraint(fields=('address',), name='unique_address'),
        ),
    ]
