# Generated by Django 2.2 on 2020-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0009_auto_20200429_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mined_count',
            old_name='timestamp',
            new_name='time_stamp',
        ),
        migrations.RenameField(
            model_name='notarised_count',
            old_name='timestamp',
            new_name='time_stamp',
        ),
        migrations.AddField(
            model_name='mined_count',
            name='count_mined',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mined_count',
            name='max_block',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mined_count',
            name='season',
            field=models.CharField(default='no_season', max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notarised_count',
            name='season',
            field=models.CharField(default='no_season', max_length=34),
            preserve_default=False,
        ),
    ]
