# Generated by Django 2.2 on 2020-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0010_auto_20200430_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarised',
            name='chain',
            field=models.CharField(max_length=32),
        ),
    ]
