# Generated by Django 2.2 on 2020-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0011_auto_20200430_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarised',
            name='opret',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
