# Generated by Django 2.2 on 2020-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0013_auto_20200430_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarised',
            name='opret',
            field=models.CharField(max_length=1024),
        ),
    ]
