# Generated by Django 2.2 on 2020-05-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0014_auto_20200430_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mined_count',
            old_name='count_mined',
            new_name='blocks_mined',
        ),
        migrations.RenameField(
            model_name='mined_count',
            old_name='last_mined',
            new_name='last_mined_block',
        ),
        migrations.RenameField(
            model_name='mined_count',
            old_name='max_block',
            new_name='last_mined_blocktime',
        ),
        migrations.RenameField(
            model_name='mined_count',
            old_name='max_mined',
            new_name='max_value_mined',
        ),
        migrations.RenameField(
            model_name='mined_count',
            old_name='sum_mined',
            new_name='sum_value_mined',
        ),
    ]
