# Generated by Django 2.2 on 2020-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0015_auto_20200502_1231'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addresses',
            name='unique_address',
        ),
        migrations.AddConstraint(
            model_name='addresses',
            constraint=models.UniqueConstraint(fields=('address', 'season'), name='unique_season_address'),
        ),
    ]
