# Generated by Django 2.2 on 2020-05-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0016_auto_20200502_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarised',
            name='opret',
            field=models.CharField(max_length=2048),
        ),
    ]
