# Generated by Django 2.2 on 2020-05-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0017_auto_20200502_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='notarised_chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('ntx_count', models.PositiveIntegerField()),
                ('kmd_ntx_height', models.PositiveIntegerField()),
                ('kmd_ntx_blockhash', models.CharField(max_length=64)),
                ('kmd_ntx_txid', models.CharField(max_length=64)),
                ('lastnotarization', models.PositiveIntegerField()),
                ('opret', models.CharField(max_length=2048)),
                ('ac_ntx_block_hash', models.CharField(max_length=34)),
                ('ac_ntx_height', models.PositiveIntegerField()),
                ('ac_block_height', models.CharField(max_length=34)),
                ('ntx_lag', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'notarised_chain',
            },
        ),
    ]
