# Generated by Django 2.2 on 2020-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0018_notarised_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarised_chain',
            name='ac_ntx_block_hash',
            field=models.CharField(max_length=64),
        ),
    ]
