# Generated by Django 2.2 on 2020-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0020_auto_20200504_0252'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notarised_chain',
            constraint=models.UniqueConstraint(fields=('chain',), name='unique_chain'),
        ),
    ]
