# Generated by Django 2.2 on 2020-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0021_auto_20200504_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='notary_id',
            field=models.CharField(max_length=34),
        ),
    ]
