# Generated by Django 2.2 on 2020-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0022_auto_20200504_0957'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notarised_count',
            constraint=models.UniqueConstraint(fields=('notary', 'season'), name='unique_notary_season'),
        ),
    ]
