# Generated by Django 2.2 on 2020-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0023_auto_20200504_1123'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mined_count',
            constraint=models.UniqueConstraint(fields=('notary', 'season'), name='unique_notary_season_mined'),
        ),
    ]
