# Generated by Django 2.2 on 2020-05-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0024_auto_20200504_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=34)),
                ('notary', models.CharField(max_length=34)),
                ('utxo_count', models.PositiveIntegerField()),
                ('eligible_utxo_count', models.PositiveIntegerField()),
                ('oldest_utxo_block', models.PositiveIntegerField()),
                ('balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rewards', models.DecimalField(decimal_places=8, max_digits=18)),
                ('update_time', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.AddConstraint(
            model_name='rewards',
            constraint=models.UniqueConstraint(fields=('address',), name='unique_reward_address'),
        ),
    ]
