# Generated by Django 2.2 on 2020-05-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0025_auto_20200505_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary', models.CharField(max_length=34)),
                ('chain', models.CharField(max_length=34)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('address', models.CharField(max_length=34)),
                ('update_time', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.AddConstraint(
            model_name='balances',
            constraint=models.UniqueConstraint(fields=('notary', 'chain'), name='unique_notary_chain_balance'),
        ),
    ]
