# Generated by Django 2.2 on 2020-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0026_auto_20200505_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='update_time',
            field=models.PositiveIntegerField(),
        ),
    ]
