# Generated by Django 2.2 on 2020-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0027_auto_20200505_0622'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balances',
            name='unique_notary_chain_balance',
        ),
        migrations.AddConstraint(
            model_name='balances',
            constraint=models.UniqueConstraint(fields=('notary', 'chain', 'address'), name='unique_notary_chain_addr_balance'),
        ),
    ]
