# Generated by Django 2.2 on 2020-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0028_auto_20200505_0843'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addresses',
            name='unique_season_coin_address',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='coin',
            new_name='chain',
        ),
        migrations.AddConstraint(
            model_name='addresses',
            constraint=models.UniqueConstraint(fields=('address', 'season', 'chain'), name='unique_season_chain_address'),
        ),
    ]
