# Generated by Django 2.2 on 2020-05-07 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0029_auto_20200506_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=34)),
                ('coins_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('electrums', django.contrib.postgres.fields.jsonb.JSONField()),
                ('electrums_ssl', django.contrib.postgres.fields.jsonb.JSONField()),
                ('explorers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dpow', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'coins',
            },
        ),
        migrations.AddConstraint(
            model_name='coins',
            constraint=models.UniqueConstraint(fields=('chain',), name='unique_chain_coin'),
        ),
    ]
