# Generated by Django 2.2 on 2020-05-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0030_auto_20200507_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notarised_count',
            old_name='json_count',
            new_name='chain_ntx_counts',
        ),
    ]
