# Generated by Django 2.2 on 2020-05-08 03:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0031_auto_20200508_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarised_count',
            name='chain_ntx_pct',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
