# Generated by Django 2.2 on 2020-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0032_notarised_count_chain_ntx_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mined',
            name='season',
            field=models.CharField(default='unknown', max_length=34),
            preserve_default=False,
        ),
    ]
