# Generated by Django 2.2 on 2020-05-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0034_auto_20200508_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='active_dpow',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coins',
            name='mm2_compatible',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
