# Generated by Django 2.2 on 2020-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0035_auto_20200509_0311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mined',
            name='unique_block',
        ),
        migrations.RenameField(
            model_name='mined',
            old_name='block',
            new_name='block_height',
        ),
        migrations.RenameField(
            model_name='notarised',
            old_name='block_ht',
            new_name='block_height',
        ),
        migrations.RenameField(
            model_name='notarised',
            old_name='prev_block_ht',
            new_name='prev_block_height',
        ),
        migrations.AddConstraint(
            model_name='mined',
            constraint=models.UniqueConstraint(fields=('block_height',), name='unique_block'),
        ),
    ]
