# Generated by Django 2.2 on 2020-05-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0036_auto_20200509_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='active_dpow',
            new_name='dpow_active',
        ),
    ]
