# Generated by Django 2.2 on 2020-05-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0037_auto_20200509_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='notary_name',
            new_name='owner_name',
        ),
    ]
