# Generated by Django 2.2 on 2020-05-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0038_auto_20200509_0600'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balances',
            name='unique_notary_chain_addr_balance',
        ),
        migrations.AddField(
            model_name='balances',
            name='season',
            field=models.CharField(default='unknown', max_length=34),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='balances',
            constraint=models.UniqueConstraint(fields=('notary', 'chain', 'season'), name='unique_notary_chain_season_balance'),
        ),
    ]
