# Generated by Django 2.2 on 2020-05-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0040_notarised_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notarised_chain',
            old_name='kmd_ntx_height',
            new_name='block_height',
        ),
    ]
