# Generated by Django 2.2 on 2020-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0041_auto_20200509_0945'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notarised_chain',
            name='unique_chain',
        ),
        migrations.AddField(
            model_name='notarised_chain',
            name='season',
            field=models.CharField(default='Season_3', max_length=34),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='notarised_chain',
            constraint=models.UniqueConstraint(fields=('chain', 'season'), name='unique_notarised_chain_season'),
        ),
    ]
