# Generated by Django 2.2 on 2020-05-10 05:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0042_auto_20200509_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='mined_count_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mined_date', models.DateField()),
                ('notary', models.CharField(max_length=64)),
                ('blocks_mined', models.PositiveIntegerField()),
                ('sum_value_mined', models.DecimalField(decimal_places=8, max_digits=18)),
                ('max_value_mined', models.DecimalField(decimal_places=8, max_digits=18)),
                ('last_mined_block', models.PositiveIntegerField()),
                ('last_mined_blocktime', models.PositiveIntegerField()),
                ('time_stamp', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'mined_count_daily',
            },
        ),
        migrations.CreateModel(
            name='notarised_chain_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notarised_date', models.DateField()),
                ('chain', models.CharField(max_length=64)),
                ('ntx_count', models.PositiveIntegerField()),
                ('block_height', models.PositiveIntegerField()),
                ('kmd_ntx_blockhash', models.CharField(max_length=64)),
                ('kmd_ntx_txid', models.CharField(max_length=64)),
                ('lastnotarization', models.PositiveIntegerField()),
                ('opret', models.CharField(max_length=2048)),
                ('ac_ntx_block_hash', models.CharField(max_length=64)),
                ('ac_ntx_height', models.PositiveIntegerField()),
                ('ac_block_height', models.CharField(max_length=34)),
                ('ntx_lag', models.CharField(max_length=34)),
                ('season', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'notarised_chain_daily',
            },
        ),
        migrations.CreateModel(
            name='notarised_count_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notarised_date', models.DateField()),
                ('notary', models.CharField(max_length=64)),
                ('btc_count', models.PositiveIntegerField()),
                ('antara_count', models.PositiveIntegerField()),
                ('third_party_count', models.PositiveIntegerField()),
                ('other_count', models.PositiveIntegerField()),
                ('total_ntx_count', models.PositiveIntegerField()),
                ('chain_ntx_counts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('chain_ntx_pct', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time_stamp', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=34)),
            ],
            options={
                'db_table': 'notarised_count_daily',
            },
        ),
        migrations.AddConstraint(
            model_name='notarised_count_daily',
            constraint=models.UniqueConstraint(fields=('notary', 'notarised_date'), name='unique_notary_date'),
        ),
        migrations.AddConstraint(
            model_name='notarised_chain_daily',
            constraint=models.UniqueConstraint(fields=('chain', 'notarised_date'), name='unique_notarised_chain_date'),
        ),
        migrations.AddConstraint(
            model_name='mined_count_daily',
            constraint=models.UniqueConstraint(fields=('notary', 'mined_date'), name='unique_notary_daily_mined'),
        ),
    ]
