# Generated by Django 2.2 on 2020-05-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0043_auto_20200510_0544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mined_count',
            new_name='mined_count_season',
        ),
        migrations.RenameModel(
            old_name='notarised_chain',
            new_name='notarised_chain_season',
        ),
        migrations.RenameModel(
            old_name='notarised_count',
            new_name='notarised_count_season',
        ),
        migrations.AlterModelTable(
            name='mined_count_season',
            table='mined_count_season',
        ),
        migrations.AlterModelTable(
            name='notarised_count_season',
            table='notarised_count_season',
        ),
    ]
