# Generated by Django 2.2 on 2020-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0044_auto_20200510_0651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notarised_chain_season',
            table='notarised_chain_season',
        ),
    ]
