# Generated by Django 2.2 on 2020-05-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0045_auto_20200510_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mined_count_daily',
            name='season',
        ),
    ]
