# Generated by Django 2.2 on 2020-05-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0046_remove_mined_count_daily_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='ac_block_height',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='ac_ntx_block_hash',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='ac_ntx_height',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='block_height',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='kmd_ntx_blockhash',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='kmd_ntx_txid',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='lastnotarization',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='ntx_count',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='ntx_lag',
        ),
        migrations.RemoveField(
            model_name='notarised_chain_daily',
            name='opret',
        ),
    ]
