# Generated by Django 2.2 on 2020-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0048_auto_20200510_1702'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balances',
            name='unique_notary_chain_season_balance',
        ),
        migrations.RemoveField(
            model_name='mined_count_daily',
            name='last_mined_block',
        ),
        migrations.RemoveField(
            model_name='mined_count_daily',
            name='last_mined_blocktime',
        ),
        migrations.RemoveField(
            model_name='mined_count_daily',
            name='max_value_mined',
        ),
        migrations.AddConstraint(
            model_name='balances',
            constraint=models.UniqueConstraint(fields=('chain', 'address'), name='unique_chain_address_balance'),
        ),
    ]
