# Generated by Django 2.2 on 2020-05-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0049_auto_20200511_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notarised_chain_season',
            old_name='ac_ntx_block_hash',
            new_name='ac_ntx_blockhash',
        ),
    ]
