# Generated by Django 2.2 on 2020-05-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0050_auto_20200512_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='owner_name',
            new_name='notary_name',
        ),
        migrations.RenameField(
            model_name='notarised',
            old_name='prev_block_hash',
            new_name='ac_ntx_blockhash',
        ),
        migrations.RenameField(
            model_name='notarised',
            old_name='prev_block_height',
            new_name='ac_ntx_height',
        ),
        migrations.RenameField(
            model_name='notarised_chain_season',
            old_name='lastnotarization',
            new_name='kmd_ntx_blocktime',
        ),
    ]
