# Generated by Django 2.2 on 2020-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0051_auto_20200512_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='notary_name',
            new_name='notary',
        ),
    ]
