# Generated by Django 2.2 on 2020-05-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0052_auto_20200512_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='node',
            field=models.CharField(default='main', max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balances',
            name='node',
            field=models.CharField(default='main', max_length=34),
            preserve_default=False,
        ),
    ]
