# Generated by Django 2.2 on 2020-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0053_auto_20200519_0321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balances',
            name='unique_chain_address_balance',
        ),
        migrations.AddConstraint(
            model_name='balances',
            constraint=models.UniqueConstraint(fields=('chain', 'address', 'season'), name='unique_chain_address_season_balance'),
        ),
    ]
