# Generated by Django 2.2 on 2020-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0054_auto_20200519_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='chain_sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('block_height', models.PositiveIntegerField()),
                ('sync_hash', models.CharField(max_length=64)),
                ('explorer_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'chain_sync',
            },
        ),
        migrations.AddConstraint(
            model_name='chain_sync',
            constraint=models.UniqueConstraint(fields=('chain', 'block_height'), name='unique_chain_block_sync'),
        ),
    ]
