# Generated by Django 2.2 on 2020-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0055_auto_20200520_1114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chain_sync',
            name='unique_chain_block_sync',
        ),
        migrations.AddConstraint(
            model_name='chain_sync',
            constraint=models.UniqueConstraint(fields=('chain',), name='unique_chain_sync'),
        ),
    ]
