# Generated by Django 2.2 on 2020-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0057_auto_20200522_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn_social',
            name='icon',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
