# Generated by Django 2.2 on 2020-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0059_nn_social_season'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nn_social',
            name='unique_notary_social',
        ),
        migrations.AddConstraint(
            model_name='nn_social',
            constraint=models.UniqueConstraint(fields=('notary', 'season'), name='unique_notary_season_social'),
        ),
    ]
