# Generated by Django 2.2 on 2020-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0060_auto_20200523_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_notarised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('chain', models.CharField(max_length=32)),
                ('block_time', models.PositiveIntegerField()),
                ('notary', models.CharField(max_length=64)),
                ('season', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'last_notarised',
            },
        ),
        migrations.AddConstraint(
            model_name='last_notarised',
            constraint=models.UniqueConstraint(fields=('notary', 'chain'), name='unique_notary_chain'),
        ),
    ]
