# Generated by Django 2.2 on 2020-05-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0062_last_notarised_block_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_btc_notarised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary', models.CharField(max_length=64)),
                ('txid', models.CharField(max_length=64)),
                ('block_height', models.PositiveIntegerField()),
                ('block_time', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'last_btc_notarised',
            },
        ),
        migrations.AddConstraint(
            model_name='last_btc_notarised',
            constraint=models.UniqueConstraint(fields=('notary',), name='unique_notary_btc_ntx'),
        ),
    ]
