# Generated by Django 2.2 on 2020-06-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0064_auto_20200531_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='funding_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=128)),
                ('txid', models.CharField(max_length=128)),
                ('vout', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('block_hash', models.CharField(max_length=128)),
                ('block_height', models.PositiveIntegerField()),
                ('block_time', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=128)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=18)),
                ('season', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'funding_transactions',
            },
        ),
        migrations.AddConstraint(
            model_name='funding_transactions',
            constraint=models.UniqueConstraint(fields=('txid', 'vout', 'category'), name='unique_category_vout_txid_funding'),
        ),
    ]
