# Generated by Django 2.2 on 2020-06-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0065_auto_20200604_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding_transactions',
            name='address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
