# Generated by Django 2.2 on 2020-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0066_funding_transactions_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding_transactions',
            name='notary',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
