# Generated by Django 2.2 on 2020-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0067_funding_transactions_notary'),
    ]

    operations = [
        migrations.CreateModel(
            name='notarised_tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('first_ntx_block', models.PositiveIntegerField()),
                ('last_ntx_block', models.PositiveIntegerField()),
                ('first_ntx_block_time', models.PositiveIntegerField()),
                ('last_ntx_block_time', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'notarised_tenure',
            },
        ),
        migrations.AddIndex(
            model_name='last_notarised',
            index=models.Index(fields=['block_time'], name='last_notari_block_t_e573bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='notarised_tenure',
            constraint=models.UniqueConstraint(fields=('chain', 'season'), name='unique_chain_season_tenure'),
        ),
    ]
