# Generated by Django 2.2 on 2020-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0068_auto_20200621_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarised_tenure',
            name='ntx_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
