# Generated by Django 2.2 on 2020-06-23 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0069_notarised_tenure_ntx_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='notarised_btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_txid', models.CharField(max_length=64)),
                ('btc_block_hash', models.CharField(max_length=64)),
                ('btc_block_ht', models.PositiveIntegerField()),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), size=13)),
                ('notaries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), size=13)),
                ('kmd_block_hash', models.CharField(max_length=64)),
                ('kmd_block_ht', models.PositiveIntegerField()),
                ('opret', models.CharField(max_length=2048)),
                ('season', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'notarised_btc',
            },
        ),
        migrations.AddConstraint(
            model_name='notarised_btc',
            constraint=models.UniqueConstraint(fields=('btc_txid',), name='unique_btc_txid'),
        ),
    ]
