# Generated by Django 2.2 on 2020-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd_ntx_api', '0070_auto_20200623_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarised_btc',
            name='kmd_txid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        )
    ]
